### ISSUE TITLE
Stackset definition

### ISSUE THREAD

**Issue by cotiletta** [amelbakry/kube-schedule-scaler#3]
I'm trying to start the container without errors, not defining any stackset (my case, I don't need them) and I got this error:

Deployments collected for scaling:
Deployment: php-apache, Namespace: default, Replicas: None, MinReplicas: 10, MaxReplicas: None, Schedule: 30 4 * * 1,2,3,4,5
Deployment: php-apache, Namespace: default, Replicas: None, MinReplicas: 5, MaxReplicas: None, Schedule: 00 8 * * 1,2,3,4,5
Deployment: php-apache, Namespace: default, Replicas: None, MinReplicas: 7, MaxReplicas: None, Schedule: 00 21 * * 1,2,3,4,5
Deployment: php-apache, Namespace: default, Replicas: None, MinReplicas: 12, MaxReplicas: None, Schedule: 30 5 * * 6,7
Deployment: php-apache, Namespace: default, Replicas: None, MinReplicas: 2, MaxReplicas: None, Schedule: 00 9 * * 6,7
Deployment: php-apache, Namespace: default, Replicas: None, MinReplicas: 20, MaxReplicas: None, Schedule: 00 21 * * 6,7
Traceback (most recent call last):
  File "/root/schedule_scaling/schedule_scaling.py", line 274, in <module>
    stack_job_creator()
  File "/root/schedule_scaling/schedule_scaling.py", line 155, in stack_job_creator
    stacks__to_scale = stacks_to_scale()
  File "/root/schedule_scaling/schedule_scaling.py", line 127, in stacks_to_scale
    for stackset in StackSet.objects(api).filter(namespace=namespace):
  File "/usr/local/lib/python3.5/dist-packages/pykube/query.py", line 133, in __iter__
    return iter(self.query_cache["objects"])
  File "/usr/local/lib/python3.5/dist-packages/pykube/query.py", line 123, in query_cache
    cache["response"] = self.execute().json()
  File "/usr/local/lib/python3.5/dist-packages/pykube/query.py", line 108, in execute
    r.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://10.0.0.1:443/apis/zalando.org/v1/namespaces/custom-metrics/stacksets

**Comment by ekarmazin** [comment]
@cotiletta can you check https://10.0.0.1:443/apis if you have `zalando.org/v1` there at all?

**Comment by cotiletta** [comment]
it seems I'm unauthorized even if I try just https://10.0.0.1:443/apis
